//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ois_ders
    {
        public short ders_id { get; set; }
        public string ders_ad { get; set; }
        public string ders_kredi { get; set; }
        public Nullable<short> ders_okulyonetimid { get; set; }
    
        public virtual ois_ogrenciders ois_ogrenciders { get; set; }
        public virtual ois_okulyonetim ois_okulyonetim { get; set; }
    }
}
