//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ois_ogrenciders
    {
        public short ogrenciders_id { get; set; }
        public Nullable<short> ogrenciders_dersid { get; set; }
        public Nullable<short> ogrenciders_ogrenciid { get; set; }
    
        public virtual ois_ders ois_ders { get; set; }
        public virtual ois_ogrenci ois_ogrenci { get; set; }
    }
}
